language: cpp
compiler:
  - gcc
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-filesystem1.55-dev
      - libboost-program-options1.55-dev
      - libboost-regex1.55-dev
      - libboost-date-time1.55-dev
      - libboost-thread1.55-dev
      - libboost-log1.55-dev
      - libboost-locale1.55-dev
      - libboost-chrono1.55-dev
      - libblkid1
  coverity_scan:
    project:
      name: "puppetlabs/facter"
      description: "Build submitted via Travis CI"
    notification_email: michael.smith@puppetlabs.com
    build_command_prepend: "$USERDIR/bin/cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_PREFIX_PATH=$USERDIR .; make clean"
    build_command: "make"
    branch_pattern: coverity_scan

before_install:
  # Use a predefined install location; cppcheck requires the cfg location is defined at compile-time.
  - mkdir -p $USERDIR
  # grab a pre-built cmake 3.2.3
  - wget https://s3.amazonaws.com/kylo-pl-bucket/cmake-3.2.3-Linux-x86_64.tar.gz
  - tar xzvf cmake-3.2.3-Linux-x86_64.tar.gz --strip 1 -C $USERDIR
  # Install dependencies of facter
  - wget https://s3.amazonaws.com/kylo-pl-bucket/yaml-cpp-0.5.1_install.tar.bz2
  - tar xjvf yaml-cpp-0.5.1_install.tar.bz2 --strip 1 -C $USERDIR
  - wget https://github.com/puppetlabs/leatherman/releases/download/${LEATHERMAN_VERSION}/leatherman.tar.gz
  - tar xzvf leatherman.tar.gz -C $USERDIR
  - wget https://github.com/puppetlabs/cpp-hocon/releases/download/${CPPHOCON_VERSION}/cpp-hocon.tar.gz
  - tar xzvf cpp-hocon.tar.gz -C $USERDIR

script: if [ ${COVERITY_SCAN_BRANCH} != 1 ]; then ./scripts/travis_target.sh ; fi

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "Tjur2fEgZFuZIUyi5i7vs20Tw0fy586pcXjS9tyytIULgS0FHWjMi6fxeI9YrSmFSNhYrEVEJonXZvzJYgHaIJGytxtNcuZQ+nXrjw2bpOAdKk56X2ZLbC8pGPfBoVJl3Ebkm1xb9G887tW9pQLeDgIW5sb0YTNpM/dIgwWjr48="
    - USERDIR=/tmp/userdir
    - PYTHONUSERBASE=$USERDIR
    - PATH=$USERDIR/bin:$PATH
    - LD_LIBRARY_PATH=$USERDIR/lib:$LD_LIBRARY_PATH
    - LEATHERMAN_VERSION=0.8.1
    - CPPHOCON_VERSION=0.1.2
